name: edu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  bloc: ^8.1.4
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  dio: ^5.5.0+1
  get_it: ^7.7.0
  connectivity_plus: ^6.0.3
  mask_text_input_formatter: ^2.9.0
  url_launcher: ^6.3.0
  easy_localization: ^3.0.7
  hive_flutter: ^1.1.0
  flutter_bloc: ^8.1.6
  formz: ^0.7.0
  json_annotation: ^4.9.0
  go_router: ^14.2.0
  printing: ^5.12.0
  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  flutter_native_splash: ^2.4.0
  pinput: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/vectors/
    - lib/assets/videos/
    - lib/assets/fonts/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #