// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6NrxRQxDkko9Bkbhls2RnT5SWsfjhrIY',
    appId: '1:422819746758:web:605e2704c46534530158c7',
    messagingSenderId: '422819746758',
    projectId: 'rivojchat',
    authDomain: 'rivojchat.firebaseapp.com',
    storageBucket: 'rivojchat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnm2nVszz1kcSFZ9_UqrbFsE5G9T0K8-A',
    appId: '1:422819746758:android:643c815ba5ad66000158c7',
    messagingSenderId: '422819746758',
    projectId: 'rivojchat',
    storageBucket: 'rivojchat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_4ef-Su9wqQIzd-NJSjcnjWKcxG3d0zo',
    appId: '1:422819746758:ios:05ac999f4b8fa5cb0158c7',
    messagingSenderId: '422819746758',
    projectId: 'rivojchat',
    storageBucket: 'rivojchat.appspot.com',
    iosBundleId: 'com.example.edu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_4ef-Su9wqQIzd-NJSjcnjWKcxG3d0zo',
    appId: '1:422819746758:ios:05ac999f4b8fa5cb0158c7',
    messagingSenderId: '422819746758',
    projectId: 'rivojchat',
    storageBucket: 'rivojchat.appspot.com',
    iosBundleId: 'com.example.edu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6NrxRQxDkko9Bkbhls2RnT5SWsfjhrIY',
    appId: '1:422819746758:web:f03dc74dad191eb60158c7',
    messagingSenderId: '422819746758',
    projectId: 'rivojchat',
    authDomain: 'rivojchat.firebaseapp.com',
    storageBucket: 'rivojchat.appspot.com',
  );
}
